### ISSUE TITLE
WebSharper.targets breaks fsautocomplete reference detection

### ISSUE THREAD

**Issue by spiffytech** [fsharp/fsharpbinding#945] opened 2015-02-01 02:40 UTC
I've used the F# Scaffolding project to build a basic WebSharper sitelets demo. However, including the WebSharper.targets file in my .fsproj (as seems required for generating JavaScript from WebSharper) causes fsautocomplete to ignore all references in my .fsproj file (e.g., System.Web). Additionally, fsautocomplete does not detect the references for WebSharper's DLLs. Ceasing to include WebSharper.targets makes my references work (but then WebSharper's JavaScript generation doesn't).

I consider this an fsautocomplete bug, since opening my project in MonoDevelop correctly finds the signatures for all System.Web and WebSharper code.

My sample project can be found here: http://ge.tt/api/1/files/9T3Y8e92/0/blob?download

The code file in question is src/sleep_log/Library.fs.

I'm editing my project with Emacs fsharp-mode, but I've confirmed the problem with fsautocomplete.exe:

```
$ echo "project "'"'sleep_log.fsproj'"'"\nparse "'"'Library.fs'"'" sync\n$(cat Library.fs)\n<<EOF>>" | mono /home/spiffytech/dotfiles-public/.emacs.d/elpa/fsharp-mode-20150114.1450/bin/fsautocomplete.exe
DATA: project
/home/spiffytech/Documents/programs/sleep_log/src/sleep_log/Library.fs
<<EOF>>
INFO: Synchronous parsing started
<<EOF>>
DATA: errors
[3:5-3:19] ERROR The namespace or module 'IntelliFactory' is not defined
[6:7-6:21] ERROR The namespace or module 'IntelliFactory' is not defined
[7:4-7:14] ERROR The type 'JavaScript' is not defined
[11:7-11:21] ERROR The namespace or module 'IntelliFactory' is not defined
[12:7-12:21] ERROR The namespace or module 'IntelliFactory' is not defined
[16:21-16:28] ERROR The type 'Content' is not defined
[17:4-17:15] ERROR The value or constructor 'PageContent' is not defined
[18:7-18:11] ERROR The namespace or module 'Page' is not defined
[19:8-19:13] ERROR The record label 'Title' is not defined
[27:14-27:22] ERROR The type 'IWebsite' is not defined
[27:14-27:30] ERROR The type 'obj' is not an interface type
[27:14-27:22] ERROR The type 'IWebsite' is not defined
[27:14-27:22] ERROR The type 'IWebsite' is not defined
[27:14-27:30] ERROR This type is not an interface type
[28:18-28:25] ERROR No abstract property was found that corresponds to this override
[31:18-31:25] ERROR No abstract property was found that corresponds to this override
[29:8-29:15] ERROR The namespace or module 'Sitelet' is not defined
[34:19-34:22] ERROR The type 'Web' is not defined
[34:19-34:22] ERROR The type 'Web' is not defined
[34:19-34:22] ERROR The type 'Web' is not defined
[38:12-38:19] ERROR The type 'Website' is not defined
<<EOF>>
```

**Comment by rneatherway** [comment] 2015-02-01 17:37
I tried just loading your project and I found that fsautocomplete returned an error message that it couldn't find the WebSharper.targets. I assumed this would be fixed if I built the project with `./build.sh` to fetch the NuGet packages, but this failed with `Cannot open assembly '.paket/paket.bootstrapper.exe': No such file or directory.`
 
```
~/dev/Sleep Log-55f535ecd2/src/sleep_log $ echo "project "'"'sleep_log.fsproj'"'"\n" | mono ~/dev//rneatherway-fsharpbinding/FSharp.AutoComplete/bin/Debug/fsautocomplete.exe
ERROR: Project file '/home/robnea/dev/Sleep Log-55f535ecd2/src/sleep_log/sleep_log.fsproj' is invalid: '/home/robnea/dev/Sleep Log-55f535ecd2/src/sleep_log/sleep_log.fsproj: /home/robnea/dev/Sleep Log-55f535ecd2/src/sleep_log/sleep_log.fsproj could not import "../../packages/WebSharper/build/WebSharper.targets"'
<<EOF>>
```

**Comment by spiffytech** [comment] 2015-02-01 18:07
Ah, sorry about that. I didn't realize the .paket/ folder needed to be in my repo export. I've added it, and confirmed I can compile from the .zip file I'm giving you.

New zip file: http://ge.tt/api/1/files/89JYBg92/0/blob?download

**Comment by rneatherway** [comment] 2015-02-01 22:03
Could you please try fsautcomplete again after a successful compile with just the `project` command like I used? It should definitely give an error message if it can't find the references, so if that isn't happening perhaps the MELPA package contains the wrongs DLLs or something.

**Comment by spiffytech** [comment] 2015-02-01 22:28
Got tired of nested quotes, so I put the command into a text file. I get no error, and the same results if I clone and compile the fsharpbinding git repo, instead of using the fsautocomplete.exe from MELPA.

```
~/Documents/programs/sleep_log/src/sleep_log 17:24:11 spiffytech@spiffytop  (git)-[master]-_

$ cat fsauto_script.txt 
project "sleep_log.fsproj"


~/Documents/programs/sleep_log/src/sleep_log 17:24:13 spiffytech@spiffytop  (git)-[master]-_

$ cat fsauto_script.txt | mono cat fsauto_script.txt | mono /tmp/fsharpbinding/FSharp.AutoComplete/bin/Debug/fsautocomplete.exe
DATA: project
/home/spiffytech/Documents/programs/sleep_log/src/sleep_log/Library.fs
<<EOF>>
```

**Comment by rneatherway** [comment] 2015-02-03 12:52
When I try to build (on Linux with mono 3.2.8), I get the same errors as reported by fsautocomplete. I think the problem is that the Websharper DLLs are somehow getting added as references at compile-time, but this doesn't always work correctly.

```
~/Downloads/sleep_log-d7b1a2104a $ ./build.sh 
No version specified. Downloading latest stable.
Starting download from https://github.com/fsprojects/Paket/releases/download/0.26.4/paket.exe
Paket version 0.26.4.0
found: /home/robin/Downloads/sleep_log-d7b1a2104a/paket.dependencies
FAKE 3.14.8 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/FAKE
Downloading FSharp.Compiler.Service 0.0.82 to /home/robin/.local/share/NuGet/Cache/FSharp.Compiler.Service.0.0.82.nupkg
Downloading SourceLink.Fake 0.4.2 to /home/robin/.local/share/NuGet/Cache/SourceLink.Fake.0.4.2.nupkg
Downloading WebSharper 2.5.134.72 to /home/robin/.local/share/NuGet/Cache/WebSharper.2.5.134.72.nupkg
Downloading NUnit 2.6.4 to /home/robin/.local/share/NuGet/Cache/NUnit.2.6.4.nupkg
Downloading NUnit.Runners 2.6.4 to /home/robin/.local/share/NuGet/Cache/NUnit.Runners.2.6.4.nupkg
Downloading NuGet.CommandLine 2.8.3 to /home/robin/.local/share/NuGet/Cache/NuGet.CommandLine.2.8.3.nupkg
Downloading Octokit 0.6.2 to /home/robin/.local/share/NuGet/Cache/Octokit.0.6.2.nupkg
Downloading Microsoft.Bcl.Build 1.0.21 to /home/robin/.local/share/NuGet/Cache/Microsoft.Bcl.Build.1.0.21.nupkg
Downloading Microsoft.Bcl 1.1.9 to /home/robin/.local/share/NuGet/Cache/Microsoft.Bcl.1.1.9.nupkg
Downloading Microsoft.Net.Http 2.2.28 to /home/robin/.local/share/NuGet/Cache/Microsoft.Net.Http.2.2.28.nupkg
Downloading FSharp.Formatting 2.6.3 to /home/robin/.local/share/NuGet/Cache/FSharp.Formatting.2.6.3.nupkg
NUnit 2.6.4 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/NUnit
SourceLink.Fake 0.4.2 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/SourceLink.Fake
WebSharper 2.5.134.72 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/WebSharper
NUnit.Runners 2.6.4 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/NUnit.Runners
NuGet.CommandLine 2.8.3 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/NuGet.CommandLine
Microsoft.Bcl.Build 1.0.21 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/Microsoft.Bcl.Build
Microsoft.Bcl 1.1.9 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/Microsoft.Bcl
Microsoft.Net.Http 2.2.28 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/Microsoft.Net.Http
FSharp.Formatting 2.6.3 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/FSharp.Formatting
Octokit 0.6.2 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/Octokit
FSharp.Compiler.Service 0.0.82 unzipped to /home/robin/Downloads/sleep_log-d7b1a2104a/packages/FSharp.Compiler.Service
8 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
<== RunTests
<== Build
<== AssemblyInfo
   <== Clean

The resulting target order is:
 - Clean
 - AssemblyInfo
 - Build
 - RunTests
 - All
Starting Target: Clean 
Creating /home/robin/Downloads/sleep_log-d7b1a2104a/bin
Creating /home/robin/Downloads/sleep_log-d7b1a2104a/temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "src/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: /home/robin/Downloads/sleep_log-d7b1a2104a/sleep_log.sln
  xbuild  /home/robin/Downloads/sleep_log-d7b1a2104a/sleep_log.sln /t:Rebuild    /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"/home/robin/Downloads/sleep_log-d7b1a2104a/packages/FAKE/tools/FakeLib.dll"
xbuild  /home/robin/Downloads/sleep_log-d7b1a2104a/sleep_log.sln /t:Rebuild    /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"/home/robin/Downloads/sleep_log-d7b1a2104a/packages/FAKE/tools/FakeLib.dll"
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 03/02/2015 12:36:25.
__________________________________________________
Project "/home/robin/Downloads/sleep_log-d7b1a2104a/sleep_log.sln" (Rebuild target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Release|Any CPU".
	Target Rebuild:
		Project "/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/sleep_log.fsproj" (Rebuild target(s)):
			Target RestorePackages:
				Executing: mono --runtime=v4.0.30319 /home/robin/Downloads/sleep_log-d7b1a2104a/.paket/paket.exe restore
				Paket version 0.26.4.0
				found: /home/robin/Downloads/sleep_log-d7b1a2104a/paket.dependencies
				0 seconds - ready.
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
				Created directory "obj/Release/"
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target CoreCompile:
				Tool /usr/lib/cli/fsharp/fsc.exe execution started with arguments: -o:obj/Release/sleep_log.dll --debug:pdbonly --noframework --define:TRACE --doc:../../bin/sleep_log.xml --optimize+ -r:/usr/lib/mono/4.0/mscorlib.dll -r:/usr/lib/mono/4.0/System.dll -r:/usr/lib/mono/4.0/System.Numerics.dll -r:/usr/lib/mono/4.0/System.Web.dll -r:/usr/lib/mono/4.0/System.Core.dll --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --highentropyva- Library.fs 
				F# Compiler for F# 3.1 (Open Source Edition)
				Freely distributed under the Apache 2.0 Open Source License
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(3,6): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(6,8): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(7,8): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(8,8): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(9,5): error FS0039: The type 'JavaScript' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(11,5): error FS0039: The type 'JavaScript' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(13,5): error FS0039: The type 'JavaScript' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(15,5): error FS0039: The value or constructor 'Div' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(16,9): error FS0039: The value or constructor 'OnAfterRender' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(18,6): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(20,11): error FS0039: The namespace or module 'Web' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(20,11): error FS0039: The namespace or module 'Web' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(21,5): error FS0039: The type 'JavaScript' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(22,15): error FS0859: No abstract property was found that corresponds to this override
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(20,11): error FS0039: The namespace or module 'Web' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(25,8): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(26,8): error FS0039: The namespace or module 'IntelliFactory' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(30,22): error FS0039: The type 'Content' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(31,5): error FS0039: The value or constructor 'PageContent' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(32,8): error FS0039: The namespace or module 'Page' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(33,9): error FS0039: The record label 'Title' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(43,15): error FS0039: The type 'IWebsite' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(43,15): error FS0887: The type 'obj' is not an interface type
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(43,15): error FS0039: The type 'IWebsite' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(43,15): error FS0039: The type 'IWebsite' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(43,15): error FS0908: This type is not an interface type
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(44,19): error FS0859: No abstract property was found that corresponds to this override
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(47,19): error FS0859: No abstract property was found that corresponds to this override
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(45,9): error FS0039: The namespace or module 'Sitelet' is not defined
/home/robin/Downloads/sleep_log-d7b1a2104a/src/sleep_log/Library.fs(54,13): error FS0039: The type 'Website' is not defined
```

**Comment by rneatherway** [comment] 2015-02-05 10:17
This is an upstream FCS bug, see https://github.com/fsharp/FSharp.Compiler.Service/issues/294

**Comment by rneatherway** [comment] 2015-06-04 13:58
I'm not 100% sure what fixed this, but it is resolved in the latest version of FCS and therefore in emacs.

**Closed by rneatherway** 2015-06-04 13:58 UTC
Labels: Emacs
