### ISSUE TITLE
vim: CursorHold event clears type def messages

### ISSUE THREAD

**Issue by cbowdon** [fsharp/fsharpbinding#914] opened 2015-01-06 11:04 UTC
If I hit leader t to get a type def, it disappears quickly. I think the CursorHold event is responsible because if I mash "hlhlhlhlhl..." then the message stays until I stop mashing. This is in vim74.

**Comment by kjnilsson** [comment] 2015-01-06 19:41
Strange. I don't get this behaviour at all for me the type signature message stays around until the next message occurs or I type a command.

**Comment by cbowdon** [comment] 2015-01-06 21:03
I've found this starts happening only after first saving the file. I get this with:

* latest fsharpbinding and syntastic
* a clean Ubuntu 14.04 VM
* Mono, F# from the Xamarin package repo
* vim74 from Ubuntu package repo

It's not happening for me on OS X with otherwise the same setup. Something to do with the vim build maybe?

**Comment by mavnn** [comment] 2015-01-07 10:52
I thought this was by design; it normally stays up just long enough to be read and then disappears.

**Comment by kjnilsson** [comment] 2015-01-07 11:10
It is not. :) This sounds like a potential issue with vim itself. AFAIK
CursorHold shouldn't be re-triggered after doing a leader command as that
is how it works on my mac. I need to set up a linux dev env and do some
more testing.

On 7 January 2015 at 10:52, Michael Newton <notifications@github.com> wrote:

> I thought this was by design; it normally stays up just long enough to be
> read and then disappears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsharp/fsharpbinding/issues/914#issuecomment-69006273>
> .
>



-- 
*Karl Nilsson*
twitter: @kjnilsson
blog: coderkarl.wordpress.com

**Comment by kjnilsson** [comment] 2015-01-07 14:17
Ok so it looks like macvim behaves differently from normal vim here. Could either or both of you try my fork and see if it improves the experience? ttps://github.com/kjnilsson/fsharpbinding

**Comment by cbowdon** [comment] 2015-01-07 21:25
Yeah that seems to resolve it in the setup I described above.

**Comment by kjnilsson** [comment] 2015-01-08 09:44
ok I've merged this fix in. Closing. Thanks for testing.

**Closed by kjnilsson** 2015-01-08 09:44 UTC
Labels: Vim
